### ISSUE TITLE
The repl freezes for several seconds every time you type `db`

### ISSUE THREAD

**Issue by sgiacomel** [egoist/prisma-repl#16]
I am going to present a problem and offer a workaround here.
I found out by using the repl that every time you type `db`, the console freezes for several second.
This seems to happen because the whole prisma object gets inspected and possibly logged.
To avoid that, you can use a custom inspect function (https://devdocs.io/node/util#utilinspectcustom)
For example, after starting the repl, we can type:
```
const customInspectSymbol = Symbol.for('nodejs.util.inspect.custom');
db[customInspectSymbol] = function () { return '' };
```
and that would prevent the freezes.
Also posted here: https://github.com/prisma/prisma/issues/18320

**Comment by amake** [comment]
It would be nice if this workaround could be done in the prisma-repl code so that we don't have to do it manually every time.
